name: build-arm
run-name: Build the static binaries (arm64)
on: [push]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-24.04-arm
    steps:
      - name: download repo
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: run build
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo ./build.sh
          sudo ./release.sh
  
      - name: create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: misc/shimboot-binaries*